### ISSUE TITLE
1.0 todo list

### ISSUE THREAD

**Issue by orta** [danger/danger-js#225]
- [x] Expose Docs to the site somehow #218 
- [x] Expose a GitHub API object to the DSL #227 
- [x] Fix windows build #224, #273 
- [x] Write blog post on Artsy blog https://github.com/artsy/artsy.github.io/pull/347
- [x] Do a design for JS Danger.Systems - http://danger.systems/js/
- [x] Port guides from Ruby, add JS specifics -  http://danger.systems/js/guides.html
- [x] API Reference page on site
- [x] Inline auto-completed editor on site
- [x] Revise the home page
- [x] Update VISION.md
- [x] Wait on a Jest update #261

**Comment by orta** [comment]
Some design ideas have been shipped to https://github.com/danger/design

General gist is that the main logo is a mask around different @cloudyconway images, on the site it'll be pulling a new BG on every deploy, as an asset pack, I'll pick a few of my favs and put them here. For example like these.

![danger_2](https://cloud.githubusercontent.com/assets/49038/25073517/6b5b4208-22b6-11e7-9195-f53f8ea51f7f.png)

![danger_1](https://cloud.githubusercontent.com/assets/49038/25073519/6fd38336-22b6-11e7-8cf6-f5e48b3c2e87.png)
![danger_3](https://cloud.githubusercontent.com/assets/49038/25073520/6fe5ab1a-22b6-11e7-8dc7-a79b4347ddcc.png)
![danger_4](https://cloud.githubusercontent.com/assets/49038/25073521/6fe5c456-22b6-11e7-8853-9db5a161da24.png)

The website is starting to come together, at least enough so that I can test some of the layout infra

**Comment by orta** [comment]
0.21 contained revised docs, I've shipped a tonne of site updatse

**Comment by orta** [comment]
it mainly just needs a weekend polish pass

**Comment by orta** [comment]
Given most of the polish pass now, most docs are feeling good. I'd like to do some more work on the inline editor but other than that. I'm happy to go.

**Comment by orta** [comment]
Blog is ready

**Comment by orta** [comment]
Inline docs are all good as of #295 - README/VISION also got an update yesterday

**Comment by orta** [comment]
I can live without the Jest update. So we're going 👍

**Comment by orta** [comment]
Fixed by #301
